### ISSUE TITLE
Security Issue from `lodash`

### ISSUE THREAD

**Issue by liuw2000** [qlik-oss/http-metrics-middleware#139]
### Description

Twistlock found a security issue in `lodash` (<4.17.19) that is introduced by `http-metrics-middleware`

<img width="527" alt="Screen Shot 2020-10-08 at 5 10 41 PM" src="https://user-images.githubusercontent.com/20097296/95514065-57044800-0989-11eb-9d61-1ebe6c790fb6.png">

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

### Versions

* Node.js:
* Express or Koa:
* Operating system:
* [Other relevant versions]

**Comment by hairyhenderson** [comment]
This has since been updated - I'll release a new version of this module.

**Comment by hairyhenderson** [comment]
Fixed in v2.2.1 https://www.npmjs.com/package/http-metrics-middleware/v/2.1.1
